### ISSUE TITLE
老师，Latex转word有高招吗？

### ISSUE THREAD

**Issue by findyy99** [LaureatePoet/HFUT_Course_Report_Template#5]
格式乱了就算了，表格表头和数据也会丢失，哇哇哇！！！:( 救救我，各大论坛找遍了。
这是表格代码，[这是完整代码](https://docs.google.com/document/d/1ORzGGr-WztP4Ft4LKrMPMC1vwPwDyfkCxe5JIfpe_mc/edit?usp=sharing)
<img width="884" alt="截屏2020-06-11 下午11 08 32" src="https://user-images.githubusercontent.com/26852735/84403887-c87cf580-ac38-11ea-9e4e-24853e602a37.png">

在PDF里面是好好的
<img width="493" alt="截屏2020-06-11 下午12 21 58" src="https://user-images.githubusercontent.com/26852735/84404050-f5310d00-ac38-11ea-8136-a57ae54ad1f2.png">
用pandoc转到docx里面就缺胳膊少腿的
<img width="838" alt="截屏2020-06-11 下午11 13 16" src="https://user-images.githubusercontent.com/26852735/84404257-2e697d00-ac39-11ea-9698-6b3a427aa691.png">

**Comment by LaureatePoet** [comment]
先说 PDF转DOC 比较流行的工具是pandadoc，但我可能更偏向 直接使用`Adobe Acrobat`强行转换。

至于你提到的问题：**表格表头和数据也会丢失**，这种很正常，现在似乎没有比较成熟的方案，你可以使用`Adobe Acrobat`试试。

----
有个问题，既然都编辑好了，直接交PDF不就可以吗？为什么要转换成DOC呢？

----
p.s.我不是老师😂，如果你有问题，也可以去 [CTAN](https://www.ctan.org/)、[LaTexStuido](https://www.latexstudio.net/)去看看。
还有个**QQ Group：91940767**，里面专家前辈不少，还是蛮热心的。

**Comment by findyy99** [comment]
@LaureatePoet 谢谢！

1. `Adobe Acrobat`是可以PDF转DOC，转完字体间距什么都变了，太难了

 

2. 因为不算是太正经的课设，老师要提交word，Latex写的是挺爽，转换可就难受了

3. 好嘞，谢谢学长（学姐）！！！

**Comment by LaureatePoet** [comment]
那就用更暴力的方法，PDF 转成 图片， 图片贴到word里面。没得问题。
----
不客气（我可能是学长/学弟

**Comment by findyy99** [comment]
@LaureatePoet 巨佬，请受我一拜！！！🤪🤪

**Comment by LaureatePoet** [comment]
@findyy99 另外提示一点：贴代码，可以去[这里](https://paste.ubuntu.com/)

**Comment by findyy99** [comment]
@LaureatePoet 谢谢！👍
